USE job_portal;

-- demo password for all inserted accounts: password
-- hash generated by PHP password_hash('password', PASSWORD_DEFAULT)
SET @pwd = '$2y$10$wH4xQ2A7Q9kQxq2S0j2D0e8aQJ9fY5qQm4LwQ7Vj2vM5xFh9V9p7S';

INSERT IGNORE INTO users (id, name, email, password_hash, phone, role, is_active, is_verified, created_at) VALUES
(1001, 'Recruiter One', 'recruiter@jobportal.test', @pwd, '01700000000', 'recruiter', 1, 1, NOW()),
(1002, 'Employer One', 'employer@jobportal.test', @pwd, '01800000000', 'employer', 1, 1, NOW()),
(1003, 'Seeker One', 'seeker1@jobportal.test', @pwd, '01900000001', 'seeker', 1, 1, NOW()),
(1004, 'Seeker Two', 'seeker2@jobportal.test', @pwd, '01900000002', 'seeker', 1, 1, NOW());

INSERT IGNORE INTO recruiter_profiles (user_id, agency_name, specialization, description, website)
VALUES (1001, 'Talent Bridge', 'Software Hiring', 'Tech recruiter agency', 'https://talentbridge.test');

INSERT IGNORE INTO employer_profiles (user_id, company_name, industry, company_size, description, website, address)
VALUES (1002, 'Acme Software Ltd', 'Software', '51-200', 'Product company', 'https://acme.test', 'Dhaka');

INSERT IGNORE INTO seeker_profiles (user_id, headline, summary, skills, years_experience, education_level, current_salary, expected_salary, preferred_location, resume_path)
VALUES
(1003, 'PHP Developer', 'Backend developer', 'PHP,MySQL,Laravel', 2, 'BSc CSE', 40000, 55000, 'Dhaka', NULL),
(1004, 'Frontend Engineer', 'UI engineer', 'JavaScript,React,CSS', 3, 'BSc CSE', 50000, 65000, 'Dhaka', NULL);

INSERT IGNORE INTO categories (id, name, description) VALUES
(201, 'Software Engineering', 'Developer roles'),
(202, 'Design', 'Design roles');

INSERT IGNORE INTO recruiter_clients (id, recruiter_id, employer_id, company_name_override, added_at)
VALUES
(301, 1001, 1002, NULL, NOW()),
(302, 1001, NULL, 'Standalone Client Ltd', NOW());

INSERT IGNORE INTO jobs (id, employer_id, recruiter_id, category_id, title, description, requirements, benefits, salary_min, salary_max, location, job_type, experience_level, deadline, status, is_featured, created_at)
VALUES
(401, 1002, 1001, 201, 'Junior PHP Developer', 'Build web modules', 'PHP, MySQL', 'Health Insurance', 30000, 60000, 'Dhaka', 'full-time', 'entry', '2026-12-31', 'active', 0, NOW()),
(402, 1001, 1001, 201, 'React Frontend Engineer', 'Build UI dashboards', 'React, REST API', 'Hybrid Work', 45000, 80000, 'Dhaka', 'full-time', 'mid', '2026-12-31', 'active', 0, NOW());

INSERT IGNORE INTO applications (id, job_id, seeker_id, recruiter_id, cover_letter, resume_path, status, applied_at)
VALUES
(501, 401, 1003, NULL, 'Interested in this role.', NULL, 'submitted', NOW()),
(502, 401, 1004, NULL, 'I have relevant experience.', NULL, 'reviewed', NOW()),
(503, 402, 1004, NULL, 'Strong frontend background.', NULL, 'shortlisted', NOW());
